### PR TITLE
Set TK_SILENCE_DEPRECATION=1 to suppress this warning.

### PR DESCRIPTION
**Pull request by spotanjo3**
What is this ? I am using macOS Catalina. First time I have seen it. It wasn't there before but it is still working, thought. I want to get rid of it every time I use RCM with it through terminal. Help ?

### CODE REVIEW

**Comment by trainboy2019** [comment]
@azoreseuropa what do you mean?

**Comment by spotanjo3** [comment]
> @azoreseuropa what do you mean?

Hi. When I launch fusee-launcher-master and I got this message from terminal:

> Welcome to Fusée Gelée launcher for macOS
> Please ensure that your Switch is in RCM mode!
> DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.

That's what I got.

**Comment by spotanjo3** [comment]
Help ??

**Comment by trainboy2019** [comment]
Are you able to run the program?

**Comment by spotanjo3** [comment]
Yes I am able to thought but it wasn't there before until I upgrade to Catalina.

**Comment by trainboy2019** [comment]
I think it's just a heads up that the version of TK is going to be sunset in the future

**Comment by spotanjo3** [comment]
Ahh... Just ignored it for now?

**Comment by trainboy2019** [comment]
Yup.

**Pull request closed without merging**
